url: "https://eig-niger.antoine-augusti.fr"
baseurl: ""
title: "EIG.ne"
lang: fr
email: contact@eig.ne
twitter: # TODO
facebook: # TODO

sass:
    style: compressed

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "projets"
    values:
      layout: "projet"

collections:
  projets:
    output: true
    permalink: /projets/:year/:title.html
